# Generated by Django 4.1.13 on 2024-07-01 20:01

import bson.objectid
from django.db import migrations, models
import django_api.models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('last_connexion', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', djongo.models.fields.EmbeddedField(model_container=django_api.models.Players)),
                ('nb_players', models.IntegerField(default=None, null=True)),
                ('nb_partie', models.IntegerField(default=None, null=True)),
                ('nb_dices', models.IntegerField(default=None, null=True)),
                ('timer', models.IntegerField(default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
